[da]
# The JWT used to authenticate with the avail light client. Instructions for generating this token can be found in the README
avail_rpc_auth_token = "MY.SECRET.TOKEN"
# The address of the *trusted* avail light client to interact with
avail_rpc_address = "http://127.0.0.1:8000"  #change ? - light-client-addressl
# The largest response the rollup will accept from the avail node. Defaults to 100 MB
max_avail_response_body_size = 104_857_600
# The maximum time to wait for a response to an RPC query against avail node. Defaults to 60 seconds.
avail_rpc_timeout_seconds = 60

[storage]
# The path to the rollup's data directory. Paths that do not begin with `/` are interpreted as relative paths.
path = "demo_data"

# We define the rollup's genesis to occur at block number `start_height`. The rollup will ignore
# any blocks before this height
[runner]
start_height = 3  #change the start height...

[runner.rpc_config]
# the host and port to bind the rpc server for
bind_host = "127.0.0.1"
bind_port = 12345

[prover_service]
aggregated_proof_block_jump = 1